### ISSUE TITLE
[Bug report] macOS 11.3: GrandOrgue crashes from time to time

### ISSUE THREAD

**Issue by uctcs** [oleg68/GrandOrgue#22]
I observe GrandOrgue crashes from time to time. GrandOrgue disappears from the screen without an error message. Attached is a crash report.

[GrandOrgue_2021-04-30-034234.crash.zip](https://github.com/oleg68/GrandOrgue/files/6402582/GrandOrgue_2021-04-30-034234.crash.zip)

**Comment by oleg68** [comment]
Do you use GO built by you or the one from Github release? Does the problem still exist?

**Comment by uctcs** [comment]
Yes, I use the version from your website. And yes, it happens quite often. In most cases when closing the application, but sometimes when I open a window.

**Comment by oleg68** [comment]
Could you reproduce it with a build with debug info included and attach the crsash report ?https://github.com/oleg68/GrandOrgue/suites/2634692559/artifacts/57801114

**Comment by uctcs** [comment]
Attached you will find an archive with the screenshot of an error message and a crash report. I had to start GO only twice.

[Archiv.zip](https://github.com/oleg68/GrandOrgue/files/6412408/Archiv.zip)

**Comment by oleg68** [comment]
@uctcs  Please try the build from there https://github.com/oleg68/GrandOrgue/actions/runs/807546730

Seems I've fixed the crashes.

**Comment by oleg68** [comment]
Progress bar  is another cracshing cause. I've pushed the fix. Try the build https://github.com/oleg68/GrandOrgue/actions/runs/807731228 when it becomes ready (green).

**Comment by oleg68** [comment]
@uctcs the new build is ready: https://github.com/oleg68/GrandOrgue/actions/runs/807731228

**Comment by uctcs** [comment]
Still the same. I have to hide (cmd-h) and unhide GO once before it works correctly.

And I had one crash report less.

[GrandOrgue_2021-05-03-210508.crash.zip](https://github.com/oleg68/GrandOrgue/files/6417073/GrandOrgue_2021-05-03-210508.crash.zip)

**Comment by oleg68** [comment]
What action was you doing when GO crashed?

**Comment by uctcs** [comment]
This is hard to say. I do not see any crash, but when I look for the log files, the report is there.

I will try to leave this folder open to see when the report is created.

**Comment by oleg68** [comment]
Does GO crashes when opening or resizing pannels?

**Comment by oleg68** [comment]
> This is hard to say. I do not see any crash, but when I look for the log files, the report is there.

The time logged in https://github.com/oleg68/GrandOrgue/files/6417073/GrandOrgue_2021-05-03-210508.crash.zip was 2021-05-03 19:51:33.152 +0200. But the build finished at Mon, 03 May 2021 18:47:27 GMT, i.e. 20:47:27 +0200. So your crash report is from previous build.

**Comment by uctcs** [comment]
Attached you will find 3 more crash reports, all running your latest build (12). The first two reports were triggered as follows:

- I started GO
- I clicked the green button --> black screen
- Hitting Esc (twice)

The program crashes without an error message.

The third crash report was triggered as follows:

- I started the GO
- I hit cmd-h (the menu bar changes to another program, e.g. finder, but the window is still on the screen).
- I clicked on the GO icon in the dock
- I opened and closed a few panels
- I closed GO

After I closed GO the report appeared in the console. GO seemed to work normally until then.

[Archive.zip](https://github.com/oleg68/GrandOrgue/files/6417442/Archive.zip)

**Comment by oleg68** [comment]
@uctcs

> I clicked the green button --> black screen

Which window did you click the green button on?

> I closed GO

How did you close GO exactly? I cann't reproduce your stack of closing mentioned in the crash report.

**Comment by oleg68** [comment]
@uctcs Please try https://github.com/oleg68/GrandOrgue/actions/runs/809779497

The build has a workaround that prevents crashing on exit GO with the stack above.

I could not catch the root cause of the crash: seems some windows events are set in incorrect order or are sent twice, but I cann't reproduce it in my environment.

So it is possible that crash will appear with some another stack. If so attach the new crash report.

**Comment by uctcs** [comment]
Yes, the close program crash seems to be tackled.

The other, which happens, when I go fullscreen without having hit cmd-h before is still present.

[GrandOrgue_2021-05-04-214956.crash.zip](https://github.com/oleg68/GrandOrgue/files/6423571/GrandOrgue_2021-05-04-214956.crash.zip)

**Comment by uctcs** [comment]
> @uctcs
> 
> > I clicked the green button --> black screen
> 
> Which window did you click the green button on?

The green button of the panel window. This main window, which has all menus does not need to be fullscreen. I tried it anyhow. Same effect -- the screen turns black.

> 
> > I closed GO
> 
> How did you close GO exactly? I can't reproduce your stack of closing mentioned in the crash report.

Two options. When I move the mouse to the top of the screen I can close the program with the menu. If cmd-tab out of the black screen, I can right-click on the GO icon and choose 'Quit'.

**Comment by oleg68** [comment]
Try https://github.com/oleg68/GrandOrgue/actions/runs/812987602

**Comment by uctcs** [comment]
Oleg, I am very sorry, but it still does not work. These videos used your latest build 18. I created 2 videos, which depict the problem.

Video 1: I started the video after GO was fully loaded. I clicked the green button and the screen turns black. I did not yet find a way to come out of the black screen apart from quitting the program. This is what I did.

Video 2: I started the video again after GO was fully loaded. At about 2 s I hit cmd-h. Normally the windows should disappear. But they stay on screen. But you see that the menu bar changes to the Finder. I click then on the dock icon and the menu changes back to GO. Now the green button work as expected. Side note: when the green button works correctly, the panels also open correctly.

Working with GO currently works pretty well after hitting once cmd-h and bringing GO back to front.

https://user-images.githubusercontent.com/82236523/117137890-a9380b00-adaa-11eb-9916-fa08391d4c2b.mov

The second video is too large for upload. You can download it here: https://www.dropbox.com/t/aQxpFitGky8wekfJ

**Comment by oleg68** [comment]
This issue is about crashing, not about the black screen. Are there still crashing or no?

**Comment by uctcs** [comment]
My apologies! I got those 2 issues messed up.

No, I have not yet managed to crash GO again, although I tried hard.

**Comment by oleg68** [comment]
https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2338-4.os
